### ISSUE TITLE
review a prezentace (sprit 2) projektu

### ISSUE THREAD

**Issue by teplyond** [kovariktomas/KovarikSimek#10]
Jak jsme na tom s review, prezentací a hodnotícím excelem?
máme to stihnout do 30 podle Průvodce a do 31 podle seenowdo. 
Nechci rejpat, ale chci dostat zápočet :-D 

@kovariktomas , @JiriSimek mám to udělat?

**Comment by teplyond** [comment]
[Uploading hodnoceni-draft.zip…]()

**Comment by teplyond** [comment]
https://www.dropbox.com/s/3iw051qvntmokqz/hodnoceni-draft.xlsx?dl=0

**Comment by JiriSimek** [comment]
V klidu, jak jsem slíbil, tak udělám. Prezentaci nahraju v průběhu dneška/zítřka...

**Comment by JiriSimek** [comment]
Hele, me ten DropBox nejde doplnovat, tak tam za me dopis taky same jednicky u vsech asi, a je to...

**Comment by kovariktomas** [comment]
@teplyond Ten excel mi také nejde otevřít. Nahraj ho na git a já se na to podívám. Já zase udělám to review. Dneska už to nebude. Uvidím jak to stihnu ale nejdýl do 31. 12. to tady bude.

**Comment by teplyond** [comment]
@kovariktomas , @JiriSimek  v pohodě, času dost. Já jen aby se na to nezapomnělo :-).

**Comment by kovariktomas** [comment]
@teplyond tak ted zbývá jen prezentace

**Comment by JiriSimek** [comment]
Tak jo, prezentace done...
