### ISSUE TITLE
Řízení kvality

### ISSUE THREAD

**Issue by teplyond** [kovariktomas/KovarikSimek#2]
čau, potřebuji abyste se podívali na "projektový plán -> Řízení kvality", v pondělí jsem bohužel nebyl na přednášce, tak přesně nevím jak to má vypadat. 
S bodem **4.5 Použité nástroje, techniky a metody** si nevím rady, to co jsem udělal je určitě blbě!

**Comment by kovariktomas** [comment]
kouknu na to

**Comment by teplyond** [comment]
Napiš co si myslíš, že by tam mělo být (já jsem vařil z vody, protože nevím)

**Comment by JiriSimek** [comment]
Zkusím se nad tím zamyslet...
