### ISSUE TITLE
Testování před koncem Sprintu1

### ISSUE THREAD

**Issue by JiriSimek** [kovariktomas/KovarikSimek#3]
Provedeme každý na své verzi testování nynějších funkcí, abychom byli připraveni na příští týden a mohli si být naší funkčností jisti. O víkendu ideálně uděláme spustitelný release, abychom jej mohli v Pondělí prezentovat jako funkční program.

Odhalené chyby postnout sem, ideálně se zamyslet i nad jejich odstraněním.

**Comment by JiriSimek** [comment]
V SeeNowDo má každý vytvořený jeden task (Sprint2) na Testování.

**Comment by kovariktomas** [comment]
Testomání provedeno. Ta byba databáze na školním pc je tím, že na pc není nainstalován sql server. Tuto bybu na školním pc nelze opravit jelikoz nejsme admin
