### ISSUE TITLE
Prezentace 

### ISSUE THREAD

**Issue by kovariktomas** [kovariktomas/KovarikSimek#4]
@JiriSimek ahoj dnes ma byt odevzdana prezentace

**Comment by kovariktomas** [comment]
Jak na tom si?

**Comment by JiriSimek** [comment]
Pár dodělávek a upnu ji sem.

**Comment by JiriSimek** [comment]
Ok, prezentace je tam. V tom SeeNowDo to v té Dokumentaci completneme az pristi tejden?

**Comment by kovariktomas** [comment]
@JiriSimek OK, v seenow až přístí tejden at´je pěkná čára

**Comment by kovariktomas** [comment]
ještě nahraj pdf verzi kdyby náhodou
