### ISSUE TITLE
Sprint retrospective

### ISSUE THREAD

**Issue by kovariktomas** [kovariktomas/KovarikSimek#5]
@teplyond ahoj dnes je termín na odevzdání Sprint retrospective. Jak jsi na tom? prezentace je v přípravě a sprint review je již nahrán.

**Comment by teplyond** [comment]
ukázku jsem nenašel, je někde? 
Jinak něco málo mám (popisuju postup prací na Sprintu 1), chtěl jsem počkat až nahraješ review, aby tam nebyly nesrovnalosti. Teď jsem v práci, nahraju to večer.

**Comment by kovariktomas** [comment]
@teplyond ukázka není. Večer to bude stačit

**Comment by kovariktomas** [comment]
Jo a v see now do to přendáme až příští týden  ať je pěkná čára

**Comment by teplyond** [comment]
Retrospective - sem to ještě trochu vymazlil. 
Seenowdo - rozhodně ať se s tím můžeme pochlubit v Retrospective  Sprintu 2 .
