### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by kovariktomas** [kovariktomas/KovarikSimek#6]
@teplyond ahoj dělám na tom xml potřeboval bych aby ve vyslednem xml souboru byly pouze dni ktere zamestnanec opravdu prijde do práce. So a Ne, svatky, dovolená, atd. tam byt nemaji

**Comment by kovariktomas** [comment]
![image](https://cloud.githubusercontent.com/assets/22446962/20687712/e0637ed2-b5bd-11e6-931f-bf69d301f649.png)
 a statusy dne jsou nasledovne takže odpracovano zmenis na 1

**Comment by teplyond** [comment]
fixed
