### ISSUE TITLE
Sql

### ISSUE THREAD

**Issue by kovariktomas** [kovariktomas/KovarikSimek#7]
@teplyond ahoj posli mi tvuj connection string a já ještě doladit tu aplikaci pro oba druhy serverů

**Comment by kovariktomas** [comment]
Pak bych to commitnul a mohl by jsi dělat na té db

**Comment by kovariktomas** [comment]
Zkus si aplikaci stáhnout a spustit mělo by to být připraveno pro novou verzi. dej vědět jestli jde

**Comment by teplyond** [comment]
Magic! Jede to, vážně dobrý díky  
Tohle už asi nebude potřeba:
```
string sConnectionString =
               String.Format("{0};{1}\"{2}\"{3}",
               @"Data Source=(LocalDB)\MSSQLLocalDB",
                "AttachDbFilename=",
                 System.IO.Path.GetFullPath(@"..\..\dochazka.mdf"),
                 ";Integrated Security=True;Connect Timeout=30");
```

**Comment by kovariktomas** [comment]
Ok já to našel na internetu. Tak muže š dělat na tom jak sme se domluvili
