### ISSUE TITLE
databaze

### ISSUE THREAD

**Issue by kovariktomas** [kovariktomas/KovarikSimek#8]
![image](https://cloud.githubusercontent.com/assets/22446962/21296500/ac646e4c-c56d-11e6-963f-3d34da2706bf.png)
@teplyond ahoj musíš si vzít asi notebook a ukázat to ty

@JiriSimek

**Comment by teplyond** [comment]
- Počítač určitě vezmu.

- Problém je ve verzi serveru, zkusil jsem to opravit nějakou starou verzí z vývojový větvě, ale otestovat to nedokážu.

**Comment by kovariktomas** [comment]
pořád mi to nejde. Když tam vyměnim to mdf za tu moji verzi tak mi to jde

**Comment by teplyond** [comment]
ok tak to udělej :-)

**Comment by kovariktomas** [comment]
@teplyond mělo by to být můžeš zkusit
