### ISSUE TITLE
Nový zaměstanec

### ISSUE THREAD

**Issue by teplyond** [kovariktomas/KovarikSimek#9]
Nefunguje vkládání zaměstnance (aspoň teda u mě)

![asd](https://cloud.githubusercontent.com/assets/15941368/21296785/a9d2425c-c573-11e6-944c-3b5f6678dd2b.PNG)

na jakýkoli RC to zahlásí chybu a nic se nevloží.
@kovariktomas Mám se v tom začít rejpat?

**Comment by kovariktomas** [comment]
je to zese v databázi... u id zamestnanec musí být autoinctement

**Comment by kovariktomas** [comment]
![image](https://cloud.githubusercontent.com/assets/22446962/21296864/9b911da6-c575-11e6-9b76-c460a4fba201.png)
@ @teplyond

**Comment by kovariktomas** [comment]
tak si to tam zkus změnit a vyzkoušej jestli to jde

**Comment by teplyond** [comment]
velmi dobře, funguje to 👍 tak to pak nahraj i s tou starou DB

**Comment by kovariktomas** [comment]
@teplyond mělo by to být můžeš zkusit
